apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: nakama-backend
spec:
    template:
        metadata:
            annotations:
                run.googleapis.com/execution-environment: gen2
        spec:
            containers:
                # Main Nakama container
                - name: nakama
                  image: gcr.io/YOUR_PROJECT_ID/nakama-backend
                  ports:
                      - containerPort: 7350
                  env:
                      - name: DATABASE_ADDRESS
                        value: "postgres:localdb@localhost:5432/nakama?sslmode=disable"
                  resources:
                      limits:
                          memory: 2Gi
                          cpu: 2

                # PostgreSQL sidecar
                - name: postgres
                  image: postgres:12.2-alpine
                  env:
                      - name: POSTGRES_DB
                        value: nakama
                      - name: POSTGRES_PASSWORD
                        value: localdb
                  ports:
                      - containerPort: 5432
                  resources:
                      limits:
                          memory: 512Mi
                          cpu: 1

                # TensorFlow Serving sidecar
                - name: tensorflow
                  image: tensorflow/serving
                  env:
                      - name: MODEL_NAME
                        value: ttt
                  ports:
                      - containerPort: 8501
                  volumeMounts:
                      - name: model
                        mountPath: /models/ttt
                  resources:
                      limits:
                          memory: 1Gi
                          cpu: 1

            volumes:
                - name: model
                  emptyDir: {}
